### ISSUE TITLE
`SerializeComponents::serialize` panics in a really vague way if a marker is invalid

### ISSUE THREAD

**Issue by expenses** [slide-rs/specs#508]
Basically, if an component contains an `Entity` but this referenced entity is deleted, then `SerializeComponent::serialize` panics with 

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::try::do_call
             at libstd/panicking.rs:326
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: core::ptr::drop_in_place
             at libcore/panicking.rs:52
   9: <core::option::Option<T>>::unwrap
             at libcore/macros.rs:20
  10: <specs::world::entity::Entity as specs::saveload::ConvertSaveload<M>>::convert_into
             at /Users/ashley/.cargo/git/checkouts/specs-18d2bb2ce407da15/b22955b/src/saveload/mod.rs:175
  11: <specs_ron_bug::Parent as specs::saveload::ConvertSaveload<MA>>::convert_into
             at src/main.rs:11
  12: <(SP,) as specs::saveload::ser::SerializeComponents<E, M>>::serialize_entity::{{closure}}
             at /Users/ashley/.cargo/git/checkouts/specs-18d2bb2ce407da15/b22955b/src/saveload/ser.rs:128
  13: <core::option::Option<T>>::map
             at libcore/option.rs:414
  14: <(SP,) as specs::saveload::ser::SerializeComponents<E, M>>::serialize_entity
             at /Users/ashley/.cargo/git/checkouts/specs-18d2bb2ce407da15/b22955b/src/saveload/ser.rs:128
  15: specs::saveload::ser::SerializeComponents::serialize
             at /Users/ashley/.cargo/git/checkouts/specs-18d2bb2ce407da15/b22955b/src/saveload/ser.rs:47
  16: <specs_ron_bug::SaveSystem as shred::system::System<'a>>::run
             at src/main.rs:48
  17: <T as shred::system::RunNow<'a>>::run_now
             at /Users/ashley/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.1/src/system.rs:125
  18: specs_ron_bug::main
             at src/main.rs:33
  19: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  20: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  21: macho_symbol_search
             at libpanic_unwind/lib.rs:103
  22: std::sys_common::bytestring::debug_fmt_bytestring
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  23: std::rt::lang_start
             at libstd/rt.rs:74
  24: <specs_ron_bug::SaveSystem as shred::system::System<'a>>::run
```

This is probably the expected behavior, but the panic could be more informative.

Example:

**Cargo.toml**:

```toml
[package]
name = "specs_ron_bug"
version = "0.1.0"
authors = ["Ashley <expenses@airmail.cc>"]

[dependencies]
ron = "*"
specs = {git = "https://github.com/slide-rs/specs", commit = "b22955b", features = ["serde"]}
specs-derive = {git = "https://github.com/slide-rs/specs", commit = "b22955b"}
serde = "*"
```

**src/main.rs**:

```rust
extern crate ron;
extern crate specs;
#[macro_use]
extern crate specs_derive;
extern crate serde;

use serde::*;
use specs::{*, saveload::*, error::*};
use ron::ser;

#[derive(Component, ConvertSaveload)]
pub struct Parent(Entity);

fn main() {
    let mut world = World::new();

    world.register::<Parent>();
    world.register::<U64Marker>();

    world.add_resource(U64MarkerAllocator::new());

    let parent = world.create_entity()
        .marked::<U64Marker>()
        .build();

    world.create_entity()
        .with(Parent(parent))
        .marked::<U64Marker>()
        .build();

    world.delete_entity(parent).unwrap();

    SaveSystem.run_now(&world.res);
}

struct SaveSystem;

impl<'a> System<'a> for SaveSystem {
    type SystemData = (
        Entities<'a>,
        ReadStorage<'a, U64Marker>,
        ReadStorage<'a, Parent>
    );

    fn run(&mut self, (entities, markers, parent): Self::SystemData) {
        let mut ser = ser::Serializer::new(Default::default(), true);

        let x: Result<(), ser::Error> = SerializeComponents::<NoError, U64Marker>::serialize(
            &(parent,),
            &entities,
            &markers,
            &mut ser
        );

        x.unwrap();
    }
}
```

**Comment by torkleyy** [comment]
Thanks for the detailed ticket! I appreciate the contribution!

The panic was in fact not expected.
